### ISSUE TITLE
Cannot access restview web server from an external client

### ISSUE THREAD

**Issue by mdear** [mgedmin/restview#29]
My development machine is in another geographical area, but I want to do rst file development and render on my local machine for speed.  It doesn't make sense to me to run my browser on the development machine for latency reasons.

restview apparently does not allow access from an external server, could you add this functionality?

For example, I run restview on machine A:
restview <file.rst> -l 8080

And on machine B, I try to access the following URL:
http://b:8080

My browser gives me an "unable to connect" error.

**Comment by mgedmin** [comment]
Try `restview -l 0:8080`.

By default restview accepts connections only from localhost, for safety/security.

**Comment by mdear** [comment]
Thanks, Marius.

Appreciate the pointer, that works as expected.

Kind regards,
<Myles>
