### ISSUE TITLE
how to alter restview parsing?

### ISSUE THREAD

**Issue by TomRoche** [mgedmin/restview#31]
I use `restview` mostly to preview documents with/on Bitbucket (BB). BB's reST parser accepts 4-char-length header/title underlines, e.g.,

    summary
    ====

However my laptop's `restview` does not: I get (e.g.)

    System Message: WARNING/2 (./README.rst, line 13)

    Title underline too short.

        summary
        ====

Hence I'd like to know, how can I change my system `restview`'s parser so as *not* to emit this warning?

**Comment by mgedmin** [comment]
You'd have to play with docutils settings like what I do here:
https://github.com/mgedmin/restview/blob/60813f51840a5c42e9c74ce3f92a79369cac8aa0/src/restview/restviewhttp.py#L464-L465

I would accept a pull request adding an option to suppress warnings.

**Comment by mgedmin** [comment]
I *think* the setting you want is [report-level](http://docutils.sourceforge.net/docs/user/config.html#report-level), but you may have to experiment.  The page I linked documents all the settings.
