### ISSUE TITLE
Supporting SVG files

### ISSUE THREAD

**Issue by Edke** [mgedmin/restview#36]
Hello.

Great job with this tool, solves missing piece for me to writing technical reports/documentations with comfort of joining code snippets and REST itself.

Found way to include images. But I often generate UML's as SVG files. And since support of modern browsers of SVG files, I guess it would be just matter of allowing another extension for images along with jpeg's and png's. When included in modern browser (Chrome ie), it will do the job from there to properly display SVG file in rendered document.

Adding this would be awesome :)

**Comment by mgedmin** [comment]
Sounds like an excellent idea!

**Comment by Edke** [comment]
Great! Will that commit be included in pypi release ?

**Comment by mgedmin** [comment]
It is now :)

**Comment by Edke** [comment]
Ok, tested and it not works, therefore investigated a bit. Serving files, your restview server is completely your code or using some python module ? Content type for svg file is incorrect, therefore I guess Chrome and Firefox wont display svg. Your response's content type is image/svg. Proper content type should be image/svg+xml.

You can hit me here when fixed and I can test locally using pip with zip, you dont have to release another release on pypi :)



![proper_response](https://cloud.githubusercontent.com/assets/115118/11246579/83f934a2-8e18-11e5-982b-c72e5a8612f1.png)

**Comment by mgedmin** [comment]
Augh!

**Comment by mgedmin** [comment]
This time I actually tested a document with an SVG image before releasing to PyPI.

**Comment by Edke** [comment]
Confirmed, working great. @mgedmin thank you for awesome quick integration !
