### ISSUE TITLE
FR: support `--version`

### ISSUE THREAD

**Issue by TomRoche** [mgedmin/restview#37]
Allowing a bug report with a version would probably be helpful, but

    me@it:~$ date ; restview --version
    Wed Dec 30 19:58:27 MST 2015
    Usage: restview [options] filename-or-directory [...]

    restview: error: no such option: --version

    me@it:~$ date ; restview --help
    Wed Dec 30 19:58:30 MST 2015
    Usage: restview [options] filename-or-directory [...]

    Serve ReStructuredText files over HTTP.

    Options:
      -h, --help            show this help message and exit
      -l PORT, --listen=PORT
                            listen on a given port (or interface:port, e.g.
                            *:8080) [default: random port on localhost]
      -b, --browser         open a web browser [default: only if -l was not
                            specified]
      -e COMMAND, --execute=COMMAND
                            run a command to produce ReStructuredText
      -w FILENAME, --watch=FILENAME
                            reload the page when a file changes (use with
                            --execute); can be specified multiple times
      --long-description    run "python setup.py --long-description" to produce
                            ReStructuredText; also enables --pypi-strict and
                            watches the usual long description sources (setup.py,
                            README.rst, CHANGES.rst)
      --css=URL|FILENAME    use the specified stylesheet; can be specified
                            multiple times [default: html4css1.css,restview.css]
      --strict              halt at the slightest problem
      --pypi-strict         enable additional restrictions that PyPI performs

**Comment by mgedmin** [comment]
I've just released restview 2.6.0 with this fix.
