### ISSUE TITLE
problems with nested lists

### ISSUE THREAD

**Issue by TomRoche** [mgedmin/restview#38]
When I create a filepath=`/tmp/restview_test.rst` with only the following contents

```reStructuredText
1. a list item
    * a nested list item
2. another list item

    * with yet another nested list item

^^^^Note the number of spaces before the bullets.
```

and render it with `restview -b /tmp/restview_test.rst &`, two problems result:

1. The generated HTML (minus the CSS and javascript) ==

```html
<div class="document">


<ol class="arabic">
<li><dl class="first docutils">
<dt>a list item</dt>
<dd><ul class="first last simple">
<li>a nested list item</li>
</ul>
</dd>
</dl>
</li>
<li><p class="first">another list item</p>
<blockquote>
<ul class="simple">
<li>with yet another nested list item</li>
</ul>
</blockquote>
</li>
</ol>
<p>^^^^Note the number of spaces before the bullets.</p>
</div>
```

2. This causes renderers (e.g., Firefox) to over-indent the nested list items: see (hopefully) attached `restview_screenshot.png`

**Comment by TomRoche** [comment]
![render problem](https://cloud.githubusercontent.com/assets/221575/12060858/b1796f26-af35-11e5-8368-e5851292eb34.png)

**Comment by TomRoche** [comment]
![render problem](/tmp/restview_screenshot.png)

**Comment by mgedmin** [comment]
AFAIU that's just how reStructuredText works:

```
This is a list:

* one
* two

This is a list inside a blockquote:

  * one
  * two
```

![ekrano nuotrauka is 2015-12-31 08-50-20](https://cloud.githubusercontent.com/assets/159967/12061948/8deb8e34-af9b-11e5-9628-9b0d59a1c792.png)

-----

The syntax you want is

```
This is a numbered list:

1. with an embedded sublist

   * one
   * two
```

i.e. align everything very precisely.  This renders to the following HTML:
```html
<p>This is a numbered list:</p>
<ol class="arabic simple">
<li>with an embedded sublist<ul>
<li>one</li>
<li>two</li>
</ul>
</li>
</ol>
```
which renders as follows:
![ekrano nuotrauka is 2015-12-31 08-54-26](https://cloud.githubusercontent.com/assets/159967/12061978/203ad9f2-af9c-11e5-9535-ce5434a2019e.png)

**Comment by mgedmin** [comment]
There's perhaps a related issue about vertical spacing.  This looks too squished for me, vertically:

![ekrano nuotrauka is 2015-12-31 09-01-39](https://cloud.githubusercontent.com/assets/159967/12062029/23238212-af9d-11e5-9b2c-6e19c050ed31.png)

This looks right:

![ekrano nuotrauka is 2015-12-31 09-02-12](https://cloud.githubusercontent.com/assets/159967/12062033/38169dee-af9d-11e5-86a5-1b7cc1f03612.png)

The only difference is I indented the last two items in:

```
This is a numbered list:

1. with an embedded sublist

   * one
   * two

2. with more items

   * one
   * two
```

The HTML gets an explicit extra `<p>` inside the outer `<li>` in the 2nd case, but not in the 1st case

```html
<p>This is a numbered list:</p>
<ol class="arabic simple">
<li>with an embedded sublist<ul>
<li>one</li>
<li>two</li>
</ul>
</li>
<li>with more items<ul>
<li>one</li>
<li>two</li>
</ul>
</li>
</ol>
```

vs 

```html
<p>This is a numbered list:</p>
<ol class="arabic">
<li><p class="first">with an embedded sublist</p>
<ul class="simple">
<li>one</li>
<li>two</li>
</ul>
</li>
<li><p class="first">with more items</p>
<blockquote>
<ul class="simple">
<li>one</li>
<li>two</li>
</ul>
</blockquote>
</li>
</ol>
```

It's a docutils bug (feature?) anyway.
