### ISSUE TITLE
FR: -B: option to *not* launch browser

### ISSUE THREAD

**Issue by TomRoche** [mgedmin/restview#46]
# summary 

I request an option (e.g., `-B`) to make `restview`

1. Start its webserver on the indicated file (as `restview -b` currently does)

2. Tell me the port on which it will be webserving (as `restview -b` currently does)

3. **Not** launch a new instance of my browser (as `restview -b` currently does)

# details 

Why I ask, and please lemme know if there's already a better way to handle my usecase:

## usecase

I am ~always running Emacs with multiple buffers and a browser with multiple tabs (usually Firefox, less often Chrome). I will edit a `file.rst` in a buffer until I wanna render it, then

1. Get the FQ filepath to `file.rst` (I have some elisp and a keybinding to do this)

2. `M-! restview -b <yank the filepath/> &` . This makes Emacs call the command in a shell and redirect stdout (etc) to another buffer.

3. `restview -b` will start webserving the HTML, and give me the URI for its rendering via a message like `Listening on http://localhost:56080/`

4. `restview -b` will try to launch my host's default browser (currently Firefox). However I already have one up, so I exit dialog=`Choose User Profile`.

5. I copy the render URI from the Emacs output buffer.

6. I find or create a browser tab, and browse to the given URI.

## recommendation

Minimally: I would like for the new option (again, just using `-B` as an example) to *not* attempt to launch the browser: just render, and tell me (via `stdout`) on what URI it's rendering (in example above, `http://localhost:56080/`). That would save me a step (step#=4 above).

Maximally: in addition to the message on `stdout` (which I would still want as a backup), `-B` should copy the URI to the user's clipboard (if one exists). That would save me another step (step#=6 above).

**Comment by mgedmin** [comment]
Sounds perfectly reasonable.

**Comment by mgedmin** [comment]
restview 2.7.0 is out.

**Comment by mgedmin** [comment]
Regarding the clipboard trick, maybe you could write a wrapper script that puts its command-line into the clipboard, e.g.

```sh
#!/bin/sh
# usage: copy-url URL
echo "$*" | xsel  # or xclip -i
echo "Copied URL to clipboard"
```

and then use `BROWSER=~/bin/copy-url restview ...` (or set BROWSER in the environment, or define a shell alias, or a 2nd wrapper script for restview)?
