### ISSUE TITLE
Setup CNTK on Linux error

### ISSUE THREAD

**Issue by yidian7** [mgedmin/restview#47]
hello
I'm facing an issue while I Building CNTK on  my macpro. Here the steps I did ,the same with the steps that Setup CNTK on Linux:
![1612bfe7-dc6f-4ac9-9be3-2cb14071938c](https://cloud.githubusercontent.com/assets/24872888/21667895/b64b952a-d337-11e6-809c-6cdb2ab624d2.png)
now ,my path is "/Users/coolatin/Documents/cntk/build/release", as here 
<img width="710" alt="b3ee6193-20fc-4329-98ca-e7792e850310" src="https://cloud.githubusercontent.com/assets/24872888/21667942/32ff18c6-d338-11e6-83a0-93c3f4fbd960.png">
 Thanks for any help you can provide.

**Comment by mgedmin** [comment]
I do not know what CNTK is.  What does it have to do with `restview`?
