### ISSUE TITLE
GPL-3.0 license is deprecated

### ISSUE THREAD

**Issue by chenrui333** [mgedmin/restview#64]
👋  [GPL-3.0](https://spdx.org/licenses/GPL-3.0.html) is a deprecated SDPX license identifier, it would be preferred to use [GPL-3.0-only](https://spdx.org/licenses/GPL-3.0-only.html) or [GPL-3.0-or-later](https://spdx.org/licenses/GPL-3.0-or-later.html) (see [here](https://spdx.org/licenses/) for details). Thanks!

cc @mgedmin

- relates to https://github.com/Homebrew/homebrew-core/pull/93006

**Comment by mgedmin** [comment]
Would you mind stating more clearly exactly where you found the deprecated SDPX license identifier? `git grep GPL-3.0` finds no matches in this git repository.

**Comment by chenrui333** [comment]
@mgedmin this is the license I referred to, https://github.com/mgedmin/restview/blob/master/LICENSE

But you should also have the license header declarations like this (reference link, https://spdx.org/licenses/GPL-3.0-or-later.html)

> Standard License Header
> <one line to give the program's name and a brief idea of what it does.>
> Copyright (C) <year> <name of author>
> 
> This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
> 
> This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
> 
> You should have received a copy of the GNU General Public License along with this program. If not, see <https://www.gnu.org/licenses/>.

**Comment by chenrui333** [comment]
Any update on this thread?

**Comment by mgedmin** [comment]
I do not understand what the problem is.

**Comment by chenrui333** [comment]
@mgedmin 👋 [this PR](https://github.com/mgedmin/restview/pull/69) would cover the issue raised in here, let me know if that makes more sense. Thanks!
